# Generated by Django 4.0.4 on 2022-07-22 06:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://cdn.pixabay.com/photo/2017/05/09/13/33/laptop-2298286_640.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
